const {test}=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const vm=require('node:vm');const c=require('./data/catalog.cjs');
function compile(file,cat){const source=fs.readFileSync(file,'utf8').split("document.addEventListener('click'")[0];const context=vm.createContext({location:{pathname:'/',search:'',hash:''},URLSearchParams});vm.runInContext(source,context);context.inputCatalog=cat;vm.runInContext('catalog=inputCatalog;discoveryCatalog=inputCatalog.home||inputCatalog;state={profile:{name:"Người chơi indie"},library:{},collections:[],comments:[],activity:[]};',context);return context;}
test('Discovery stays unchanged except the requested editorial shelf',()=>{const old=compile('research/app-before-v3.js',c.home),current=compile('app.js',c);vm.runInContext(fs.readFileSync('interiors.js','utf8'),current);for(let i=0;i<3;i++){vm.runInContext('heroIndex='+i,old);vm.runInContext('heroIndex='+i,current);assert.equal(vm.runInContext('home()',current).split('<section class="home-features">')[0],vm.runInContext('home()',old).split('<section class="home-features">')[0]);}});
test('250 distinct game records preserve all original titles and review arguments',()=>{assert.equal(c.games.length,250);assert.equal(c.home.games.length,12);assert.equal(new Set(c.games.map(g=>g.slug)).size,250);assert.equal(new Set(c.games.map(g=>g.app)).size,250);const seen=new Set();for(const g of c.games){assert.ok(g.wordCount>=(g.id<42?500:200),g.name+' is too short');assert.equal(g.sections.length,4);assert.ok(g.country&&g.theme&&g.lede&&g.verdict);for(const p of g.sections.flatMap(s=>s.paragraphs)){assert.ok(!seen.has(p),'Repeated paragraph: '+g.name);seen.add(p);}assert.ok(new Set(g.sections.map(s=>s.title)).size===4);}for(const g of c.home.games){const now=c.games.find(x=>x.slug===g.slug);assert.equal(now.name,g.name);assert.equal(now.score,g.score);}assert.equal(c.games.slice(12).filter(g=>g.score===null).length,238);});
test('Rebuilt routes use their own templates and every record renders',()=>{const context=compile('app.js',c);vm.runInContext(fs.readFileSync('interiors.js','utf8'),context);for(const g of c.games){context.game=g;const html=vm.runInContext('reviewDetail(game)',context);assert.ok(html.includes(vm.runInContext('esc(game.sections[0].title)',context)));assert.equal((html.match(/class="essay-chapter"/g)||[]).length,4);assert.ok(!html.includes('review-grid'));assert.ok(vm.runInContext('gameDetail(game)',context).includes('passport'));}for(const curation of [...c.collections,...c.legacyCollections]){context.curation=curation;assert.ok(vm.runInContext('collectionDetail(curation,false)',context).includes('series-stops'));}for(const feature of [...c.features,...c.legacyFeatures]){context.feature=feature;assert.ok(vm.runInContext('featuresPage(feature)',context).includes('essay-content'));}});

test('All articles include three distinct sourced illustrations',()=>{for(const g of c.games){assert.ok(g.images.length>=3,g.name);assert.ok(new Set(g.images.slice(0,3).map(i=>i.src)).size===3,g.name);assert.ok(g.images.every(i=>i.src.startsWith('https://')));}});

test('Country regions and practical finder apply the chosen constraints',()=>{const context=compile('app.js',c);vm.runInContext(fs.readFileSync('interiors.js','utf8'),context);context.location.pathname='/games';context.location.search='?region=south-america';const names=Array.from(vm.runInContext('filtered().map(g=>g.name)',context));assert.ok(names.includes('UNSIGHTED'));assert.ok(names.includes('VA-11 Hall-A'));assert.ok(!names.includes('FTL: Faster Than Light'));context.location.pathname='/features';context.location.search='?intent=challenge&company=coop&space=2D';const matches=vm.runInContext('chooseCandidates()',context);assert.ok(matches.length>=3);assert.ok(matches.every(g=>g.mode.includes('Co-op')&&g.type==='2D'));context.location.pathname='/games';context.location.search='';const html=vm.runInContext("browse('games')",context);assert.ok(html.includes('250 THẾ GIỚI'));assert.ok(html.includes('country-picker'));assert.ok(html.includes('BẮC MỸ'));assert.ok(!html.includes('${catalog'));});
test('All six stories have full chapters, a table of contents and three game illustrations',()=>{const context=compile('app.js',c);vm.runInContext(fs.readFileSync('interiors.js','utf8'),context);for(const f of [...c.legacyFeatures,...c.features]){context.feature=f;const html=vm.runInContext('featuresPage(feature)',context);assert.equal(f.sections.length,4);assert.equal((html.match(/class="feature-scene"/g)||[]).length,3);assert.ok(html.includes('Mục lục câu chuyện'));assert.ok(html.includes('Ghi một điều muốn thử'));assert.ok(f.sections.flatMap(s=>s.slice(1)).join(' ').split(/\s+/).length>=350);}});

test('Finder never repeats a suggestion when fewer than three games match',()=>{const context=compile('app.js',{...c,games:c.games.slice(0,150)});vm.runInContext(fs.readFileSync('interiors.js','utf8'),context);context.location.pathname='/features';context.location.search='?intent=story&company=coop&space=2D&wave=2';const matches=vm.runInContext('chooseCandidates()',context);assert.ok(matches.length>0&&matches.length<3);const html=vm.runInContext('gameFinder()',context);assert.equal((html.match(/class="finder-result-copy"/g)||[]).length,matches.length);for(const g of matches)assert.equal((html.match(new RegExp('data-edit-game="'+g.id+'"','g'))||[]).length,1);context.location.search='?intent=puzzle&company=coop&space=3D';assert.ok(vm.runInContext('gameFinder()',context).includes('Chưa có lựa chọn khớp'));});

test('Indie ideas hub offers nine distinct playable cases and preserves practical tools',()=>{const context=compile('app.js',c);vm.runInContext(fs.readFileSync('interiors.js','utf8'),context);vm.runInContext(fs.readFileSync('indie-hub.js','utf8'),context);context.location.pathname='/features';let seen=new Set();for(const key of ['knowledge','movement','everyday']){context.location.search='?lab='+key;const html=vm.runInContext('featuresPage()',context);assert.equal((html.match(/class="idea-case"/g)||[]).length,3);assert.ok(html.includes('THỬ QUAN SÁT'));for(const match of html.matchAll(/class="idea-case-photo" href="([^"]+)"/g)){assert.ok(!seen.has(match[1]));seen.add(match[1]);assert.ok(c.games.some(g=>'/games/'+g.slug===match[1]));}}assert.equal(seen.size,9);context.location.search='?mode=finder';assert.ok(vm.runInContext('featuresPage()',context).includes('data-form="game-finder"'));context.location.search='?mode=compare';assert.ok(vm.runInContext('featuresPage()',context).includes('comparison-pair'));});
test('Editorial collections work without personal collections and duet choices link distinct reviews',()=>{const context=compile('app.js',c);vm.runInContext(fs.readFileSync('interiors.js','utf8'),context);context.location.pathname='/collections';context.location.search='';const base=vm.runInContext('collectionsPage()',context);assert.ok(!base.includes('data-action="new-collection"'));assert.ok(!base.includes('Bạn tự sắp'));vm.runInContext('state.collections=[{id:123,title:"Private list"}];',context);assert.equal(vm.runInContext('collectionsPage()',context),base);for(let i=0;i<3;i++){context.location.search='?duet='+i;const html=vm.runInContext('ideaDuets()',context);const reviewLinks=[...html.matchAll(/href="\/reviews\/([^"]+)"/g)].map(m=>m[1]);assert.equal(new Set(reviewLinks).size,2);assert.ok(reviewLinks.every(slug=>c.games.some(g=>g.slug===slug)));}for(const theme of c.collections.slice(0,3))assert.ok(theme.ids.every(id=>id>=100));});

test('Asian additions preserve 150 records and make Vietnam directly discoverable',()=>{assert.deepEqual(c.games.slice(0,150),JSON.parse(fs.readFileSync('research/catalog-before-v7.json','utf8')));const added=c.games.slice(150);assert.equal(added.length,100);assert.equal(added.filter(g=>g.country==='Việt Nam').length,9);assert.equal(new Set(added.map(g=>g.country)).size,11);const context=compile('app.js',c);vm.runInContext(fs.readFileSync('interiors.js','utf8'),context);for(const g of added){context.game=g;assert.equal(vm.runInContext('countryRegion(game.country)',context),'asia');assert.equal(g.id,c.games.indexOf(g));assert.equal(g.score,null);assert.equal(g.source,'https://store.steampowered.com/app/'+g.app+'/');}context.location.pathname='/games';context.location.search='?country='+encodeURIComponent('Việt Nam');assert.equal(vm.runInContext('filtered().length',context),9);assert.ok(vm.runInContext("browse('games')",context).includes('asian-shelf'));});

