/* Discovery tools store personal evidence locally; community data has a separate service. */
const V8=(()=>{
  const D=IVDiscovery,key='indieverse-experience-v8';
  function read(){try{const x=JSON.parse(localStorage.getItem(key)||'{}');return {journal:[],dropped:{},routes:[],daily:{},...x};}catch{return {journal:[],dropped:{},routes:[],daily:{}};}}
  function write(x){localStorage.setItem(key,JSON.stringify(x));}
  const game=s=>catalog.games.find(g=>g.slug===s);
  const options=(pairs,v)=>pairs.map(([k,t])=>`<option value="${esc(k)}" ${String(v)===String(k)?'selected':''}>${esc(t)}</option>`).join('');
  function select(name,label,pairs,value=''){return `<label>${label}<select name="${name}">${options(pairs,value)}</select></label>`;}
  function tiles(ps){return `<div class="v8-grid">${ps.map(p=>{const g=game(p.slug);return g?`<article class="v8-card"><a href="${gu(g)}"><img src="${assetUrl(g.images?.[0]?.src)||img(g)}" alt="${esc(g.name)}" loading="lazy"></a><div><span class="eyebrow">${esc(g.country)} · ${p.minutes||'15'} PHÚT / PHIÊN GỢI Ý</span><h2><a href="${gu(g)}">${esc(g.name)}</a></h2><p>${esc(p.reason||g.fit)}</p><div class="button-row"><a href="${ru(g)}">Đọc nhận định ↗</a><a href="${g.source}" target="_blank" rel="noopener">Steam ↗</a></div></div></article>`:'';}).join('')}</div>`;}
  const tools=[['tonight','Tối nay chơi gì?','Một buổi chơi vừa với thời gian và tâm trạng.'],['dna','Game DNA','Nhìn lại điều khiến bạn muốn chơi tiếp.'],['mechanics','Mechanic Atlas','Theo một cơ chế qua nhiều thế giới.'],['preferences','Thích điều này, ngại điều kia','Giữ thứ bạn yêu, giảm điều khiến bạn bỏ cuộc.'],['rabbit-hole','Rabbit Hole','Rẽ theo hình ảnh, chiến đấu hoặc thế giới.'],['daily','15 phút khám phá','Một điểm hẹn nhỏ mỗi ngày.'],['radar','Comeback Radar','Lưu lý do tạm biệt, tìm lý do quay lại.'],['battle','Game Battle','Đặt hai game cạnh nhau theo từng tiêu chí.']];
  function nav(active){return `<nav class="v8-tabs" aria-label="Công cụ khám phá">${tools.map(([s,t])=>`<a href="/play/${s}" ${s===active?'aria-current="page"':''}>${t}</a>`).join('')}</nav>`;}
  function hub(){return `<section class="v8-launch"><div><span class="eyebrow">INDIEVERSE PLAY LAB</span><h2>Đừng chỉ tìm game.<br><em>Tìm cách bạn muốn chơi.</em></h2><p>Đi theo một cơ chế, một tâm trạng hay một điều bạn chưa từng thử.</p></div><div class="v8-tool-grid">${tools.map(([s,t,p],i)=>`<a href="/play/${s}"><small>0${i+1}</small><h3>${t} ↗</h3><p>${p}</p></a>`).join('')}</div></section>`;}
  function tonight(negative=false){const q=qp(),liked=q.get('like')||'hollow-knight';const ps=D.recommend(negative?{like:liked,positive:0,avoid:2,...Object.fromEntries(q)}:Object.fromEntries(q));return `<form data-v8="finder" class="v8-form">${negative?select('like','Game bạn thích',Object.keys(D.profiles).filter(game).map(s=>[s,game(s).name]),liked)+select('positive','Điều bạn muốn giữ',D.axes.map((a,i)=>[i,a]),q.get('positive')||0)+select('avoid','Điều bạn muốn ít hơn',[[-1,'Không giới hạn'],...D.axes.map((a,i)=>[i,a])],q.get('avoid')??2):select('minutes','Tôi có',[[15,'15 phút'],[30,'30 phút'],[60,'1 giờ'],[180,'3 giờ']],q.get('minutes')||60)+select('mood','Tâm trạng',[['','Bất kỳ'],['calm','Muốn thư giãn'],['curious','Muốn tò mò'],['intense','Muốn thử thách']],q.get('mood'))+select('energy','Mức tập trung',[['','Bất kỳ'],['low','Không muốn nghĩ nhiều'],['medium','Vừa phải'],['high','Sẵn sàng tập trung']],q.get('energy'))+select('activity','Muốn làm gì?',[['','Bất kỳ'],['explore','Khám phá'],['build','Xây dựng'],['story','Đọc câu chuyện'],['puzzle','Giải đố'],['combat','Hành động']],q.get('activity'))+select('coop','Chơi cùng',[['','Một mình / bất kỳ'],['yes','Cần co-op']],q.get('coop'))}<button class="primary">Tìm buổi chơi của tôi →</button></form><p class="v8-note">Đối chiếu ${Object.keys(D.profiles).length} hồ sơ được gắn đặc tính biên tập. Thời gian là gợi ý cho một phiên, không phải thời lượng hoàn thành. Hãy kiểm tra cách lưu game trước khi nghỉ.</p>${tiles(ps.slice(0,6))||'<p>Chưa có game khớp thời lượng. Thử nới thời gian.</p>'}`;}
  function dna(){const x=read(),library={};for(const [id,e]of Object.entries(state.library)){const g=catalog.games.find(g=>g.id===Number(id));if(g)library[g.slug]=e;}for(const j of x.journal)if(!library[j.slug])library[j.slug]={status:j.stage==='finished'?'completed':'playing'};for(const s of Object.keys(x.dropped))if(!library[s])library[s]={status:'paused'};const d=D.dna(library,x.journal,x.dropped);const identity=d.evidence?D.axes.map((a,i)=>({a,v:d.values[i]})).sort((a,b)=>b.v-a.v).slice(0,3).map(o=>o.a).join(' · '):'Chưa đủ dữ liệu';return `<div class="v8-dna"><div><span class="eyebrow">YOUR GAMING DNA</span><h2>${d.evidence?'Dấu vết của những lần chọn.':'DNA bắt đầu từ một lần chơi.'}</h2><strong>${identity}</strong><p>${d.evidence} game có dữ liệu đối chiếu. Đây là mô hình sở thích ước tính từ sổ tay, điểm chấm, thời gian ghi lại và lý do bỏ dở; không phải đánh giá tính cách.</p><a class="primary" href="/library">Mở sổ tay →</a><button class="outline-button" data-v8-share-dna>Chia sẻ DNA</button></div><div>${D.axes.map((a,i)=>`<div class="v8-meter"><label>${a}<b>${d.values[i]===null?'Chưa đủ dữ liệu':d.values[i]+' / 100'}</b></label><meter min="0" max="100" value="${d.values[i]||0}" aria-label="${a}"></meter></div>`).join('')}</div></div><p class="v8-note">Game đã hoàn thành có trọng số cao hơn game chỉ lưu. Chỉ các game đã có hồ sơ đặc tính mới được tính. Bạn có thể sửa hoặc xóa dữ liệu trong sổ tay.</p>`;}
  const mechanics=[
    ['time-loop','Time Loop','Một thế giới trở lại điểm đầu; hiểu biết ở lại cùng người chơi.',['outer-wilds','katana-zero'],['Outer Wilds dùng chu kỳ để biến thời điểm thành manh mối khám phá.','Katana ZERO trình bày việc thử lại như dự tính hành động, khác vòng lặp thế giới của Outer Wilds.']],
    ['parry','Parry','Đọc nhịp đối thủ và biến phòng thủ thành cơ hội.',['nine-sols','sifu','dead-cells'],['Nine Sols đặt phản đòn vào trung tâm tích Qi.','Sifu nối đỡ đòn với thế đứng và kiểm soát đám đông.','Dead Cells cho lựa chọn dùng khiên giữa nhiều kiểu trang bị.']],
    ['deck-building','Deck Building','Xây một bộ công cụ, rồi sống cùng xác suất của nó.',['slay-the-spire','inscryption','balatro'],['Slay the Spire buộc cân nhắc cả thêm lẫn bỏ lá.','Inscryption gắn bài với tài nguyên hiến tế và bối cảnh bí ẩn.','Balatro dùng Joker và biến đổi bộ bài để khuếch đại điểm.']],
    ['environment','Environmental Storytelling','Đọc câu chuyện qua không gian và dấu vết.',['hollow-knight','return-of-the-obra-dinn','inside'],['Hallownest giữ lịch sử trong kiến trúc và cư dân còn lại.','Obra Dinn giữ bằng chứng trong vị trí, đồng phục và vật dụng.','INSIDE dẫn mắt qua chuyển động và bố cục thay cho lời kể.']],
    ['physics','Physics Sandbox','Một quy luật vật lý có thể gây ra nhiều kết quả không định trước.',['noita','broforce'],['Noita mô phỏng vật liệu để lửa, chất lỏng và phép thuật tương tác.','Broforce dùng địa hình phá hủy để biến đường tiến công.']],
    ['procedural','Procedural Generation','Cấu trúc được biến đổi để mỗi lượt buộc bạn thích nghi.',['dead-cells','core-keeper'],['Dead Cells thay đổi đường đi trong các quần xã quen.','Core Keeper dựng thế giới mới quanh việc đào và tìm tài nguyên.']],
    ['grappling','Grappling Hook','Đổi một điểm bám thành quỹ đạo di chuyển.',['sanabi'],['SANABI nối đu, kéo và lao người thành nhịp vượt chướng ngại.']],
    ['dialogue','Dialogue Systems','Lời nói trở thành lựa chọn có hệ quả.',['disco-elysium','coffee-talk','undertale'],['Disco Elysium biến các kỹ năng thành tiếng nói chen vào suy nghĩ.','Coffee Talk cho đồ uống góp phần mở cuộc trò chuyện.','Undertale cho ACT và Mercy thành lựa chọn trong giao tranh.']]
  ];
  function atlas(){const id=qp().get('mechanic'),m=mechanics.find(m=>m[0]===id);return m?`<a href="/play/mechanics">← Tất cả cơ chế</a><h2>${m[1]}</h2><p>${m[2]}</p>${tiles(m[3].map((slug,i)=>({slug,reason:m[4][i]})))}`:`<div class="v8-tool-grid">${mechanics.map(([s,t,p,gs])=>`<a href="/play/mechanics?mechanic=${s}"><span class="eyebrow">${gs.length} CÁCH TRIỂN KHAI</span><h2>${t}</h2><p>${p}</p><b>Theo cơ chế →</b></a>`).join('')}</div>`;}
  function rabbit(){const slugs=(qp().get('path')||'hollow-knight').split(',').filter(s=>D.profiles[s]&&game(s)).slice(0,12);if(!slugs.length)slugs.push('hollow-knight');const current=slugs.at(-1),p=D.profiles[current];return `<div class="v8-route">${slugs.map((s,i)=>`<a href="/play/rabbit-hole?path=${slugs.slice(0,i+1).join(',')}">${esc(game(s).name)}</a>`).join('<span>→</span>')}</div><h2>Từ ${esc(game(current).name)}, bạn muốn rẽ đâu?</h2><div class="v8-grid">${[['Art',7,'Thử nghiệm'],['Combat',2,'Thử thách'],['World',0,'Khám phá']].map(([label,axis,detail])=>{const visual=label==='Art'?D.visualNeighbor(current,slugs):null;const next=visual?D.profiles[visual.slug]:Object.values(D.profiles).filter(n=>!slugs.includes(n.slug)&&game(n.slug)).sort((a,b)=>Math.abs(a.vector[axis]-p.vector[axis])-Math.abs(b.vector[axis]-p.vector[axis])||a.slug.localeCompare(b.slug))[0];return next?`<a class="v8-card" href="/play/rabbit-hole?path=${[...slugs,next.slug].join(',')}"><img src="${assetUrl(game(next.slug).images[0].src)}" alt="${esc(game(next.slug).name)}"><div><span>${label} / ${detail}</span><h3>${esc(game(next.slug).name)}</h3><p>${esc(visual?.shared.length?'Cùng ngôn ngữ hình ảnh: '+visual.shared.join(', '):next.reason)}</p></div></a>`:'';}).join('')}</div><p class="v8-note">Nhánh Art dùng nhãn phong cách do biên tập viên gắn cho 24 game; không phân tích hình ảnh tự động. Hành trình tối đa 12 điểm.</p><div class="button-row"><button class="primary" data-v8-route="${slugs.join(',')}">Lưu hành trình</button><button class="outline-button" data-action="copy-link">Chia sẻ đường đi</button><a href="/play/rabbit-hole">Bắt đầu lại</a></div><h3>Đường đi đã lưu</h3>${read().routes.map(r=>`<p><a href="/play/rabbit-hole?path=${esc(r.join(','))}">${r.map(s=>esc(game(s)?.name||s)).join(' → ')}</a></p>`).join('')||'<p>Chưa có hành trình.</p>'}`;}
  function daily(){const pool=catalog.games.filter(g=>g.steamMedia?.demos?.length),day=new Date().toISOString().slice(0,10);if(!pool.length)return '<p>Đang đối chiếu demo chính thức; chưa có demo được xác nhận.</p>';const g=pool[Math.floor(Date.now()/86400000)%pool.length],choice=read().daily[day];return `<section class="v8-daily"><img src="${assetUrl(g.images[0].src)}" alt="${esc(g.name)}"><div><span class="eyebrow">${day} / 15 PHÚT KHÁM PHÁ</span><h2>${esc(g.name)}</h2><ul><li>${esc(g.genre)}</li><li>${esc(g.fit)}</li><li>${esc(g.caution)}</li></ul><a class="primary" href="https://store.steampowered.com/app/${g.steamMedia.demos[0]}/" target="_blank" rel="noopener">Mở demo trên Steam ↗</a><p>Đặt 15 phút để thử; demo có thể dài hơn. Tình trạng demo theo lần kiểm tra nguồn gần nhất.</p><div class="button-row">${['Chơi tiếp','Muốn chơi','Không hợp'].map(t=>`<button class="outline-button" data-v8-daily="${t}" data-slug="${g.slug}" aria-pressed="${choice?.choice===t}">${t}</button>`).join('')}</div></div></section>`;}
  function radar(){const ds=Object.entries(read().dropped);return `<p>Lý do bạn dừng chơi được giữ lại để đọc bản cập nhật có mục tiêu. Chưa có nguồn xác nhận bản vá khắc phục từng lý do, nên Radar không tự kết luận game đã được sửa.</p>${ds.length?ds.map(([s,d])=>{const g=game(s);return g?`<article class="v8-panel"><h2>${esc(g.name)}</h2><p>Đã dừng vì: <strong>${esc(D.reasons[d.reason])}</strong></p><p>${esc(d.note)}</p><a class="primary" href="https://store.steampowered.com/news/app/${g.app}" target="_blank" rel="noopener">Đọc cập nhật từ nhà phát triển ↗</a><button class="outline-button" data-v8-return="${s}">Tôi đã quay lại</button></article>`:'';}).join(''):'<div class="v8-panel"><h2>Chưa có game đã bỏ dở.</h2><p>Mở một bài game và ghi lý do trong phần hành trình chơi.</p><a href="/games">Chọn game →</a></div>'}`;}
  function comparison(a,b){const x=D.profiles[a.slug],y=D.profiles[b.slug];if(!x||!y)return '<p class="v8-note">Bảng đặc tính biên tập hiện có cho 24 game được gắn hồ sơ. Hai bài đọc bên trên vẫn mở được với mọi game.</p>';return `<section class="v8-panel"><span class="eyebrow">ĐẶC TÍNH TRẢI NGHIỆM / BIÊN TẬP GẮN NHÃN</span><h2>Khác nhau ở đâu?</h2><div class="v8-compare-wrap"><table class="v8-compare"><thead><tr><th>Đặc tính</th><th>${esc(a.name)}</th><th>${esc(b.name)}</th></tr></thead><tbody>${D.axes.map((axis,i)=>`<tr><th>${esc(axis)}</th><td><meter min="0" max="5" value="${x.vector[i]}"></meter> ${x.vector[i]}/5</td><td><meter min="0" max="5" value="${y.vector[i]}"></meter> ${y.vector[i]}/5</td></tr>`).join('')}</tbody></table></div><p class="v8-note">Các số là nhãn mô tả do biên tập viên ước tính, không phải chất lượng, điểm cộng đồng hay tỷ lệ người chơi đã xác minh. Mức thử thách và grind càng cao nghĩa là trải nghiệm càng đòi hỏi ở khía cạnh đó.</p></section>`;}
  function battle(){const a=game(qp().get('a')||'hollow-knight'),b=game(qp().get('b')||'dead-cells');return `<form data-v8="battle" class="v8-form">${select('a','Game thứ nhất',catalog.games.map(g=>[g.slug,g.name]),a?.slug)}${select('b','Game thứ hai',catalog.games.map(g=>[g.slug,g.name]),b?.slug)}<button class="primary">Đặt cạnh nhau</button></form>${!a||!b||a===b?'<p>Chọn hai game khác nhau.</p>':`<div class="v8-grid">${[a,b].map(g=>`<article class="v8-panel"><h2>${esc(g.name)}</h2><p>${esc(g.fit)}</p><p>${esc(g.caution)}</p><a href="${ru(g)}">Đọc bài ↗</a></article>`).join('')}</div>${comparison(a,b)}<section class="v8-panel"><h2>Bình chọn theo trải nghiệm</h2><p>Chưa có dịch vụ bình chọn công khai được kết nối. Không có phần trăm hoặc lượt chơi được xác minh để hiển thị.</p>${['Khám phá','Chiến đấu','Câu chuyện','Chơi lại','Boss'].map(t=>`<p>${t} <span class="v8-note">— Chưa có phiếu</span></p>`).join('')}</section>`}`;}
  function page(section){const tool=tools.find(t=>t[0]===section);if(!tool)return notFound();return `${crumbs([['Góc indie','/features'],[tool[1]]])}<header class="v8-heading"><span class="eyebrow">PLAY LAB / ${tool[1]}</span><h1>${tool[1]}</h1><p>${tool[2]}</p></header>${nav(section)}${({'tonight':()=>tonight(),'preferences':()=>tonight(true),'dna':dna,'mechanics':atlas,'rabbit-hole':rabbit,'daily':daily,'radar':radar,'battle':battle}[section])()}`;}
  function journey(g){const x=read(),js=x.journal.filter(j=>j.slug===g.slug).sort((a,b)=>a.hours-b.hours||a.at.localeCompare(b.at)),d=x.dropped[g.slug];return `<section class="v8-panel" id="living-review"><span class="eyebrow">LIVING REVIEW / SỔ TAY RIÊNG</span><h2>Ấn tượng thay đổi theo giờ chơi.</h2><p>Ghi một mốc, nhìn lại sau một tuần. Các ghi chép này chỉ lưu trong trình duyệt của bạn.</p><form class="v8-form" data-v8="journal" data-slug="${g.slug}"><label>Số giờ đã chơi<input name="hours" type="number" min="0" max="100000" step="0.1" required></label>${select('stage','Mốc chơi',[['playing','Đang chơi'],['finished','Đã hoàn thành'],['revisit','Nhìn lại sau một thời gian']])}<label class="v8-wide">Cảm nhận ngắn<textarea name="text" minlength="3" maxlength="1000" required></textarea></label><button class="primary">Lưu mốc chơi</button></form><ol class="v8-timeline">${js.map(j=>`<li><strong>${j.hours} giờ · ${esc(j.stage==='finished'?'Đã hoàn thành':j.stage==='revisit'?'Nhìn lại':'Đang chơi')}</strong><time>${new Date(j.at).toLocaleDateString('vi-VN')}</time><p>${esc(j.text)}</p><button data-v8-delete-journal="${j.id}">Xóa mốc</button></li>`).join('')}</ol><details><summary>${d?'Đã bỏ dở: '+esc(D.reasons[d.reason]):'Đã bỏ dở? Ghi lại lý do'}</summary><form class="v8-form" data-v8="drop" data-slug="${g.slug}">${select('reason','Lý do chính',Object.entries(D.reasons),d?.reason)}<label>Điều muốn thấy cải thiện<input name="note" maxlength="400" value="${esc(d?.note||'')}"></label><button class="outline-button">Lưu vào Comeback Radar</button></form></details></section>`;}
  document.addEventListener('submit',e=>{const f=e.target;if(!f.dataset.v8)return;e.preventDefault();const b=Object.fromEntries(new FormData(f)),x=read();try{if(f.dataset.v8==='finder'||f.dataset.v8==='battle'){go(route()+'?'+new URLSearchParams(b));return;}if(f.dataset.v8==='journal'){x.journal.push({id:crypto.randomUUID(),slug:f.dataset.slug,hours:Number(b.hours),stage:b.stage,text:b.text,at:new Date().toISOString()});}if(f.dataset.v8==='drop')x.dropped[f.dataset.slug]={...b,at:new Date().toISOString()};write(x);render();toast('Đã lưu trong trình duyệt của bạn.');}catch{toast('Không thể lưu. Kiểm tra quyền lưu trữ của trình duyệt.');}});
  document.addEventListener('click',async e=>{const b=e.target.closest('button');if(!b)return;const x=read();try{if(b.hasAttribute('data-v8-route')){const r=b.dataset.v8Route.split(',');if(!x.routes.some(p=>p.join(',')===r.join(',')))x.routes.push(r);}else if(b.dataset.v8DeleteJournal)x.journal=x.journal.filter(j=>j.id!==b.dataset.v8DeleteJournal);else if(b.dataset.v8Return)delete x.dropped[b.dataset.v8Return];else if(b.dataset.v8Daily){x.daily[new Date().toISOString().slice(0,10)]={slug:b.dataset.slug,choice:b.dataset.v8Daily};if(b.dataset.v8Daily==='Muốn chơi'){await api('/api/library',{gameId:game(b.dataset.slug).id,status:'wishlist',rating:null,note:''});state=await api('/api/state');}}else if(b.hasAttribute('data-v8-share-dna')){const text=document.querySelector('.v8-dna').innerText;await navigator.clipboard.writeText(text+'\n'+location.origin+(window.INDIEVERSE_BASE||'')+'/play/dna');toast('Đã sao chép DNA của bạn.');return;}else return;write(x);render();toast('Đã lưu.');}catch{toast('Không thể lưu hoặc sao chép. Vui lòng thử lại.');}});
  return {page,hub,journey};
})();
const v8Features=featuresPage;
const v8AsianShelf=asianShelf;
asianShelf=function(){const chart=catalog.steamChart;if(!chart?.rows?.length)return v8AsianShelf();const n=((Number(qp().get('hot'))||0)%chart.rows.length+chart.rows.length)%chart.rows.length;const row=chart.rows[n],g=catalog.games.find(g=>g.app===row.appid);const href=i=>{const p=qp();p.set('hot',i);return '/games?'+p.toString()+'#steam-hot';};return `<section class="asian-shelf" id="steam-hot"><div class="asian-shelf-heading"><div><span class="eyebrow">STEAM CHARTS / GAME TRONG DANH MỤC</span><h2>Đang được chơi.<br><em>Đáng để ghé qua.</em></h2><p>Ảnh chụp bảng Most Played của Steam ngày ${new Date(chart.rollupDate*1000).toLocaleDateString('vi-VN')}. Thứ hạng Steam toàn cầu, không phải bình chọn của Indieverse.</p></div><div class="v8-hot-controls"><a href="${esc(href(n-1))}" aria-label="Game Steam trước">←</a><span>${n+1} / ${chart.rows.length}</span><a href="${esc(href(n+1))}" aria-label="Game Steam tiếp theo">→</a></div></div><div class="v8-daily"><a href="${g.source}" target="_blank" rel="noopener"><img style="width:100%;border-radius:14px" src="${assetUrl(g.images[0].src)}" alt="${esc(g.name)}"></a><div><span class="eyebrow">HẠNG #${row.rank} · TUẦN TRƯỚC #${row.last_week_rank||'—'}</span><h2>${esc(g.name)}</h2><p>${esc(g.fit)}</p><p>${row.peak_in_game.toLocaleString('vi-VN')} người chơi đồng thời cao nhất trong dữ liệu nguồn.</p><div class="button-row"><a class="primary" href="${g.source}" target="_blank" rel="noopener">Mở Steam ↗</a><a href="${gu(g)}">Hồ sơ game →</a></div><a href="${chart.source}" target="_blank" rel="noopener">Đối chiếu bảng Steam Charts ↗</a></div></div><div class="asian-chips"><a href="/games?country=${encodeURIComponent('Việt Nam')}#catalog-list">Game Việt Nam →</a><a href="/games?region=asia#catalog-list">Khám phá châu Á →</a></div></section>`;};
featuresPage=function(f){return f?v8Features(f):V8.hub()+v8Features();};
const v8Profile=profilePage;
profilePage=function(){return `<div class="v8-account-link"><a class="primary" href="/login">Đăng nhập / Tạo tài khoản →</a><a href="/play/dna">Xem Gaming DNA ↗</a></div>`+v8Profile();};
const v8Detail=gameDetail,v8Review=reviewDetail;
gameDetail=function(g){return v8Detail(g)+V8.journey(g)+communityPanel(g);};
reviewDetail=function(g){const concise={...g,sections:g.sections.map(s=>({...s,paragraphs:s.paragraphs.flatMap(p=>p.match(/[^.!?]+[.!?]+|[^.!?]+$/g)||[p]).slice(0,Math.max(1,Math.ceil(s.paragraphs.flatMap(p=>p.match(/[^.!?]+[.!?]+|[^.!?]+$/g)||[p]).length/2))).map(p=>p.trim())}))};concise.wordCount=[concise.lede,...concise.sections.flatMap(s=>s.paragraphs),concise.verdict].join(' ').split(/\s+/).length;concise.readTime=Math.max(1,Math.ceil(concise.wordCount/220));return v8Review(concise)+V8.journey(g)+communityPanel(g)+`<section class="v8-steam"><h2>Tiếp tục với ${esc(g.name)}</h2><a class="primary" href="${g.source}" target="_blank" rel="noopener">Xem game trên Steam ↗</a></section>`;};
