const reducedMotion=matchMedia('(prefers-reduced-motion: reduce)');
let introTimer, revealObserver, introFocus;
function dismissIntro(){clearTimeout(introTimer);const overlay=document.getElementById('intro-hook');overlay.classList.add('dismissed');document.querySelectorAll('#site-header,#page,#site-footer').forEach(el=>el.inert=false);document.body.classList.remove('intro-active');if(overlay.contains(document.activeElement))(introFocus?.isConnected?introFocus:document.getElementById('page')).focus({preventScroll:true});try{sessionStorage.setItem('iv-intro-seen','1');}catch{} }
function playIntro(replay=false){const overlay=document.getElementById('intro-hook');let seen=false;try{seen=sessionStorage.getItem('iv-intro-seen')==='1';}catch{}if((seen&&!replay)||reducedMotion.matches){dismissIntro();return;}introFocus=document.activeElement;overlay.classList.remove('dismissed');document.querySelectorAll('#site-header,#page,#site-footer').forEach(el=>el.inert=true);document.body.classList.add('intro-active');document.getElementById('intro-skip').focus({preventScroll:true});clearTimeout(introTimer);introTimer=setTimeout(dismissIntro,1700);}
document.getElementById('intro-skip').addEventListener('click',dismissIntro);
document.addEventListener('keydown',e=>{if(e.key==='Escape')dismissIntro();});
function readingProgress(){const bar=document.getElementById('reading-progress'),article=document.querySelector('.essay-content');bar.hidden=!article;if(!article)return;const top=article.getBoundingClientRect().top+scrollY,total=article.offsetHeight-innerHeight;const ratio=Math.max(0,Math.min(1,(scrollY-top)/Math.max(1,total)));const chapters=[...document.querySelectorAll('.essay-content section[id]')];let active=chapters[0]?.id;for(const chapter of chapters)if(chapter.getBoundingClientRect().top<=160)active=chapter.id;document.querySelectorAll('.essay-toc a[href^="#"]').forEach(a=>{const selected=a.hash==='#'+active;a.classList.toggle('active',selected);if(selected)a.setAttribute('aria-current','location');else a.removeAttribute('aria-current');});bar.style.transform=`scaleX(${ratio})`;}
function animatePage(){const page=document.getElementById('page');page.classList.remove('page-enter');if(!reducedMotion.matches){void page.offsetWidth;page.classList.add('page-enter');revealObserver?.disconnect();revealObserver=new IntersectionObserver(entries=>{for(const e of entries)if(e.isIntersecting){e.target.classList.add('motion-reveal');revealObserver.unobserve(e.target);}},{threshold:.08});page.querySelectorAll('.dossier-tile,.reading-row,.series-card,.essay-chapter,.thought-index article,.editor-desks article,.series-stops li').forEach((el,i)=>{el.style.setProperty('--delay',(i%4)*55+'ms');revealObserver.observe(el);});}requestAnimationFrame(readingProgress);}
window.addEventListener('scroll',readingProgress,{passive:true});window.addEventListener('resize',readingProgress,{passive:true});
document.addEventListener('error',e=>{const el=e.target;if(el.tagName!=='IMG'||el.dataset.fallback)return;const match=/\/apps\/(\d+)\//.exec(el.src),app=el.dataset.app||match?.[1];if(!app)return;el.dataset.fallback='1';el.src=`https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/${app}/header.jpg`;const caption=el.closest('figure')?.querySelector('figcaption');if(caption)caption.textContent='Artwork quảng bá chính thức · Steam';},true);
playIntro();boot();
